export const copy = {
  en: {
    markets: 'Markets', why: 'Why Vanta', terminal: 'The terminal', launch: 'Launch app', start: 'Start trading', explore: 'Explore markets',
    hero: ['Your edge.', 'Never', 'offline.'], intro: 'Markets don’t sleep. Neither does your ambition.', sub: 'One workspace. Every opportunity. Always on.',
    marketTitle: ['The market moves.', 'Make your move.'], marketIntro: 'Find your next setup.', marketSub: 'Put your strategy to the test.', sample: 'DEMO MARKET DATA',
    demo: 'Demo environment', perpetual: 'perpetual', buy: 'Buy / Long', sell: 'Sell / Short', market: 'Market', limit: 'Limit', available: 'Available balance', size: 'Order size', limitPrice: 'Limit price', leverage: 'Leverage', margin: 'Margin', positionSize: 'Position size', open: 'Open demo position', place: 'Place limit order', positions: 'Positions', orders: 'Open orders', history: 'Order history', empty: 'Your next move starts here.', emptySub: 'Open a demo position to test the terminal.', noOrders: 'No pending orders.', noHistory: 'Your completed trades will appear here.', demoNote: 'Simulated prices. Virtual funds. Real practice.', close: 'Close', cancel: 'Cancel', entry: 'Entry price', pnl: 'Unrealized P&L', closed: 'Closed', cancelled: 'Cancelled', pending: 'Pending', invalid: 'Enter a valid amount from $1 up to your available balance.', invalidLimit: 'Enter a positive limit price.', opened: 'Demo position opened.', placed: 'Limit order placed. It fills when the simulated price reaches your limit.', closeNotice: 'Position closed. Virtual balance updated.', cancelNotice: 'Order cancelled. Reserved margin released.', maxOrders: 'Maximum 20 active positions and orders.', reset: 'Reset demo', resetNotice: 'Demo reset. Your virtual balance is $10,000.', full: 'Expand terminal', exitFull: 'Exit expanded terminal',
    focus: 'FOCUS ON YOUR NEXT MOVE', less: 'Less noise.', more: 'More conviction.', whyIntro: 'A considered workspace for clear decisions. Built around the way you trade.',
    features: [['See the whole picture', 'Switch markets and timeframes without losing your perspective.'], ['Make it your own', 'Choose your direction. Set your size. Practice on your terms.'], ['Stay in the flow', 'From your first chart to your next move. On any screen.']],
    next: 'The next move', yours: 'is yours.', launchTerminal: 'Launch the terminal', top: 'Back to top', disclaimer: 'Demo experience. No real funds or transactions.', pause: 'Pause motion', play: 'Resume motion', menu: 'Toggle menu', skip: 'Skip to content', chart: 'Simulated candlestick price chart',
  },
  ru: {
    markets: 'Рынки', why: 'Почему Vanta', terminal: 'Терминал', launch: 'Открыть терминал', start: 'Начать торговлю', explore: 'Смотреть рынки',
    hero: ['Твоё преимущество.', 'Всегда', 'онлайн.'], intro: 'Рынки не спят. Твои амбиции — тоже.', sub: 'Один терминал. Все возможности. Всегда на связи.',
    marketTitle: ['Рынок в движении.', 'Твой следующий ход.'], marketIntro: 'Найди свою возможность.', marketSub: 'Проверь стратегию на практике.', sample: 'ДЕМО-КОТИРОВКИ',
    demo: 'Демо-режим', perpetual: 'бессрочный', buy: 'Купить / Лонг', sell: 'Продать / Шорт', market: 'Рыночный', limit: 'Лимитный', available: 'Доступный баланс', size: 'Размер ордера', limitPrice: 'Лимитная цена', leverage: 'Плечо', margin: 'Маржа', positionSize: 'Объём позиции', open: 'Открыть демо-позицию', place: 'Создать лимитный ордер', positions: 'Позиции', orders: 'Ордера', history: 'История', empty: 'Твой следующий ход — здесь.', emptySub: 'Открой демо-позицию и проверь терминал.', noOrders: 'Нет ожидающих ордеров.', noHistory: 'Здесь появятся завершённые сделки.', demoNote: 'Демо-котировки. Виртуальный баланс. Настоящая практика.', close: 'Закрыть', cancel: 'Отменить', entry: 'Цена входа', pnl: 'Нереализованный P&L', closed: 'Закрыта', cancelled: 'Отменён', pending: 'Ожидает', invalid: 'Укажи сумму от $1 до доступного баланса.', invalidLimit: 'Укажи положительную лимитную цену.', opened: 'Демо-позиция открыта.', placed: 'Ордер создан. Он исполнится, когда демо-цена достигнет лимита.', closeNotice: 'Позиция закрыта. Виртуальный баланс обновлён.', cancelNotice: 'Ордер отменён. Маржа возвращена.', maxOrders: 'Не более 20 активных позиций и ордеров.', reset: 'Сбросить демо', resetNotice: 'Демо сброшено. На виртуальном балансе $10 000.', full: 'Развернуть терминал', exitFull: 'Свернуть терминал',
    focus: 'СОСРЕДОТОЧЬСЯ НА СЛЕДУЮЩЕМ ХОДЕ', less: 'Меньше шума.', more: 'Больше ясности.', whyIntro: 'Продуманное пространство для взвешенных решений. В твоём ритме.',
    features: [['Вся картина целиком', 'Меняй рынки и таймфреймы, сохраняя фокус на главном.'], ['На твоих условиях', 'Выбери направление, задай объём и проверь свою стратегию.'], ['Оставайся в потоке', 'От первого графика до следующей сделки. На любом экране.']],
    next: 'Следующий ход', yours: 'за тобой.', launchTerminal: 'Открыть терминал', top: 'Наверх', disclaimer: 'Демо-версия. Без реальных средств и сделок.', pause: 'Остановить анимации', play: 'Включить анимации', menu: 'Открыть меню', skip: 'Перейти к содержимому', chart: 'Демонстрационный свечной график',
  },
};
